/*
Copyright 2021 The Everoute Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	activeprobev1alpha1 "github.com/everoute/everoute/pkg/apis/activeprobe/v1alpha1"
	clientset "github.com/everoute/everoute/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/everoute/everoute/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/everoute/everoute/pkg/client/listers_generated/activeprobe/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ActiveProbeInformer provides access to a shared informer and lister for
// ActiveProbes.
type ActiveProbeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ActiveProbeLister
}

type activeProbeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewActiveProbeInformer constructs a new informer for ActiveProbe type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewActiveProbeInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredActiveProbeInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredActiveProbeInformer constructs a new informer for ActiveProbe type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredActiveProbeInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ActiveprobeV1alpha1().ActiveProbes().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ActiveprobeV1alpha1().ActiveProbes().Watch(context.TODO(), options)
			},
		},
		&activeprobev1alpha1.ActiveProbe{},
		resyncPeriod,
		indexers,
	)
}

func (f *activeProbeInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredActiveProbeInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *activeProbeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&activeprobev1alpha1.ActiveProbe{}, f.defaultInformer)
}

func (f *activeProbeInformer) Lister() v1alpha1.ActiveProbeLister {
	return v1alpha1.NewActiveProbeLister(f.Informer().GetIndexer())
}
