---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lynx-controller
  namespace: kube-system
  labels:
    app: lynx
    component: lynx-controller
spec:
  strategy:
    # Ensure the existing Pod is killed before the new one is created.
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: lynx
      component: lynx-controller
  template:
    metadata:
      labels:
        app: lynx
        component: lynx-controller
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      serviceAccountName: lynx-controller
      hostNetwork: true
      containers:
        - name: lynx-controller
          image: lynx/release
          imagePullPolicy: IfNotPresent
          command: ["lynx-controller"]
          args:
            - --enable-leader-election=true
            - --port=9443
            - -v=0
