
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: lynx-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  verbs:
  - patch
  - create
  - update
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agent.lynx.smartx.com
  resources:
  - agentinfos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - group.lynx.smartx.com
  resources:
  - groupmembers
  - groupmemberspatches
  - endpointgroups
  verbs:
  - patch
  - create
  - update
  - delete
  - deletecollection
  - get
  - list
  - watch
- apiGroups:
  - security.lynx.smartx.com
  resources:
  - tiers
  - securitypolicies
  - securitypolicies/status
  - endpoints
  - endpoints/status
  verbs:
  - patch
  - update
  - get
  - list
  - watch
- apiGroups:
  - policyrule.lynx.smartx.com
  resources:
  - policyrules
  - policyrules/status
  verbs:
  - patch
  - create
  - update
  - delete
  - deletecollection
  - get
  - list
  - watch
