
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: lynx-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agent.lynx.smartx.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - group.lynx.smartx.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - security.lynx.smartx.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - policyrule.lynx.smartx.com
  resources:
  - '*'
  verbs:
  - '*'
