---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validator.lynx.smartx.com
webhooks:
  - clientConfig:
      # CaBundle must set as the ca for secret lynx-controller-tls.
      caBundle: Cg==
      service:
        name: lynx-validator-webhook
        namespace: kube-system
        path: /validate/crds
        port: 9443
    failurePolicy: Fail
    name: validator.lynx.smartx.com
    rules:
      - apiGroups:
          - security.lynx.smartx.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - securitypolicies
          - tiers
          - endpoints
      - apiGroups:
          - group.lynx.smartx.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - endpointgroups

---
apiVersion: v1
kind: Service
metadata:
  name: lynx-validator-webhook
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
    - port: 9443
      protocol: TCP
      # This port should match port lynx-controller exposed.
      targetPort: 9443
  selector:
    app: lynx
    component: lynx-controller
