---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: everoute-agent
rules:
- apiGroups:
  - agent.everoute.io
  resources:
  - agentinfos
  verbs:
  - patch
  - create
  - update
  - delete
  - get
  - list
  - watch
- apiGroups:
    - ""
  resources:
    - pods
    - nodes
    - services
  verbs:
    - patch
    - create
    - update
    - delete
    - get
    - list
    - watch
- apiGroups:
    - group.everoute.io
  resources:
    - groupmembers
    - groupmemberspatches
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - security.everoute.io
  resources:
    - securitypolicies
    - globalpolicies
    - endpoints
    - endpoints/status
  verbs:
    - get
    - list
    - update
    - delete
    - watch
    - create
- apiGroups:
    - service.everoute.io
  resources:
    - serviceports
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - ipam.everoute.io
  resources:
    - ippools
    - ippools/status
  verbs:
    - patch
    - update
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - apps
  resources:
    - statefulsets
  verbs:
    - update
    - get
    - watch
    - list
