linters-settings:
  errcheck:
    # [deprecated] comma-separated list of pairs of the form pkg:regex
    # the regex is used to ignore names within pkg. (default "fmt:.*").
    exclude-functions:
    - fmt:.*
    - io/ioutil:^Read.*
    - io:Close
  lll:
    line-length: 170
  funlen:
    lines: 100
    statements: 80
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com
          - k8s.io
          - sigs.k8s.io
        deny: []

run:
  timeout: 30m
  issues-exit-code: 1

issues:
  exclude-files:
    - ".*_test.go$"
    - "plugin/tower/pkg/server/fake/graph/resolver/*.resolvers.go"
  exclude-dirs:
    - tests/e2e

linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace
