apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: everoute
build:
  artifacts:
    - image: everoute/release
      docker:
        dockerfile: build/images/release/Dockerfile
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
      - deploy/everoute.yaml
