/*
Copyright The Everoute Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v1alpha1 "github.com/everoute/everoute/pkg/apis/pod/v1alpha1"
	scheme "github.com/everoute/everoute/pkg/client/clientset_generated/clientset/scheme"
)

// K8sClustersGetter has a method to return a K8sClusterInterface.
// A group's client should implement this interface.
type K8sClustersGetter interface {
	K8sClusters(namespace string) K8sClusterInterface
}

// K8sClusterInterface has methods to work with K8sCluster resources.
type K8sClusterInterface interface {
	Create(ctx context.Context, k8sCluster *v1alpha1.K8sCluster, opts v1.CreateOptions) (*v1alpha1.K8sCluster, error)
	Update(ctx context.Context, k8sCluster *v1alpha1.K8sCluster, opts v1.UpdateOptions) (*v1alpha1.K8sCluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.K8sCluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.K8sClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.K8sCluster, err error)
	K8sClusterExpansion
}

// k8sClusters implements K8sClusterInterface
type k8sClusters struct {
	client rest.Interface
	ns     string
}

// newK8sClusters returns a K8sClusters
func newK8sClusters(c *PodV1alpha1Client, namespace string) *k8sClusters {
	return &k8sClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the k8sCluster, and returns the corresponding k8sCluster object, and an error if there is any.
func (c *k8sClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.K8sCluster, err error) {
	result = &v1alpha1.K8sCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("k8scluster").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of K8sClusters that match those selectors.
func (c *k8sClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.K8sClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.K8sClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("k8scluster").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested k8sClusters.
func (c *k8sClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("k8scluster").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a k8sCluster and creates it.  Returns the server's representation of the k8sCluster, and an error, if there is any.
func (c *k8sClusters) Create(ctx context.Context, k8sCluster *v1alpha1.K8sCluster, opts v1.CreateOptions) (result *v1alpha1.K8sCluster, err error) {
	result = &v1alpha1.K8sCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("k8scluster").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(k8sCluster).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a k8sCluster and updates it. Returns the server's representation of the k8sCluster, and an error, if there is any.
func (c *k8sClusters) Update(ctx context.Context, k8sCluster *v1alpha1.K8sCluster, opts v1.UpdateOptions) (result *v1alpha1.K8sCluster, err error) {
	result = &v1alpha1.K8sCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("k8scluster").
		Name(k8sCluster.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(k8sCluster).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the k8sCluster and deletes it. Returns an error if one occurs.
func (c *k8sClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("k8scluster").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *k8sClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("k8scluster").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched k8sCluster.
func (c *k8sClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.K8sCluster, err error) {
	result = &v1alpha1.K8sCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("k8scluster").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
