---
apiVersion: v1
data:
  agentconfig.yaml: |
    datapathConfig:
      {{ .Values.bridgeName }}: {{ .Values.bridgeName }}
    enableCNI: {{ .Values.enableCNI }}
    CNIConf:
      localGwIP: {{ .Values.CNIConf.localGwIP }}
      # enable everoute proxy
      enableProxy: {{ .Values.CNIConf.enableProxy }}
      # use overlay mode
      # encapMode: geneve
      {{- if ne .Values.CNIConf.encapMode "" }}
      encapMode: {{ .Values.CNIConf.encapMode }}
      {{- end}}
  cni-conf.conflist: |
    {
        "cniVersion": "0.3.0",
        "name": "everoute",
        "plugins": [
            {
                "type": "everoute"
            },
            {
                "type": "portmap",
                "capabilities": {"portMappings": true}
            }
        ]
    }
  controllerconfig.yaml: |
    enableCNI: {{ .Values.enableCNI }}
    CNIConf:
      # enable everoute proxy
      enableProxy: {{ .Values.CNIConf.enableProxy }}
      # use overlay mode
      # encapMode: geneve
      {{- if ne .Values.CNIConf.encapMode "" }}
      encapMode: {{ .Values.CNIConf.encapMode }}
      {{- end}}
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: everoute
  name: everoute-config-xu73od84d3
  namespace: kube-system