/*
Copyright 2021 The Everoute Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/everoute/everoute/pkg/apis/activeprobe/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ActiveProbeLister helps list ActiveProbes.
type ActiveProbeLister interface {
	// List lists all ActiveProbes in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.ActiveProbe, err error)
	// Get retrieves the ActiveProbe from the index for a given name.
	Get(name string) (*v1alpha1.ActiveProbe, error)
	ActiveProbeListerExpansion
}

// activeProbeLister implements the ActiveProbeLister interface.
type activeProbeLister struct {
	indexer cache.Indexer
}

// NewActiveProbeLister returns a new ActiveProbeLister.
func NewActiveProbeLister(indexer cache.Indexer) ActiveProbeLister {
	return &activeProbeLister{indexer: indexer}
}

// List lists all ActiveProbes in the indexer.
func (s *activeProbeLister) List(selector labels.Selector) (ret []*v1alpha1.ActiveProbe, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ActiveProbe))
	})
	return ret, err
}

// Get retrieves the ActiveProbe from the index for a given name.
func (s *activeProbeLister) Get(name string) (*v1alpha1.ActiveProbe, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("activeprobe"), name)
	}
	return obj.(*v1alpha1.ActiveProbe), nil
}
