/*
Copyright 2021 The Lynx Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	groupv1alpha1 "github.com/smartxworks/lynx/pkg/apis/group/v1alpha1"
	clientset "github.com/smartxworks/lynx/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/smartxworks/lynx/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/smartxworks/lynx/pkg/client/listers_generated/group/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VPortGroupInformer provides access to a shared informer and lister for
// VPortGroups.
type VPortGroupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VPortGroupLister
}

type vPortGroupInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewVPortGroupInformer constructs a new informer for VPortGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVPortGroupInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVPortGroupInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredVPortGroupInformer constructs a new informer for VPortGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVPortGroupInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GroupV1alpha1().VPortGroups().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GroupV1alpha1().VPortGroups().Watch(context.TODO(), options)
			},
		},
		&groupv1alpha1.VPortGroup{},
		resyncPeriod,
		indexers,
	)
}

func (f *vPortGroupInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVPortGroupInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *vPortGroupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&groupv1alpha1.VPortGroup{}, f.defaultInformer)
}

func (f *vPortGroupInformer) Lister() v1alpha1.VPortGroupLister {
	return v1alpha1.NewVPortGroupLister(f.Informer().GetIndexer())
}
