---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lynx-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lynx-agent
subjects:
  - kind: ServiceAccount
    name: lynx-agent
    namespace: kube-system
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    # support use certs authentication
    name: lynx-agent
