/*
Copyright The Everoute Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/everoute/everoute/pkg/apis/group/v1alpha1"
)

// FakeGroupMemberses implements GroupMembersInterface
type FakeGroupMemberses struct {
	Fake *FakeGroupV1alpha1
}

var groupmembersesResource = schema.GroupVersionResource{Group: "group.everoute.io", Version: "v1alpha1", Resource: "groupmembers"}

var groupmembersesKind = schema.GroupVersionKind{Group: "group.everoute.io", Version: "v1alpha1", Kind: "GroupMembers"}

// Get takes name of the groupMembers, and returns the corresponding groupMembers object, and an error if there is any.
func (c *FakeGroupMemberses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GroupMembers, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(groupmembersesResource, name), &v1alpha1.GroupMembers{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GroupMembers), err
}

// List takes label and field selectors, and returns the list of GroupMemberses that match those selectors.
func (c *FakeGroupMemberses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GroupMembersList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(groupmembersesResource, groupmembersesKind, opts), &v1alpha1.GroupMembersList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GroupMembersList{ListMeta: obj.(*v1alpha1.GroupMembersList).ListMeta}
	for _, item := range obj.(*v1alpha1.GroupMembersList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested groupMemberses.
func (c *FakeGroupMemberses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(groupmembersesResource, opts))
}

// Create takes the representation of a groupMembers and creates it.  Returns the server's representation of the groupMembers, and an error, if there is any.
func (c *FakeGroupMemberses) Create(ctx context.Context, groupMembers *v1alpha1.GroupMembers, opts v1.CreateOptions) (result *v1alpha1.GroupMembers, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(groupmembersesResource, groupMembers), &v1alpha1.GroupMembers{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GroupMembers), err
}

// Update takes the representation of a groupMembers and updates it. Returns the server's representation of the groupMembers, and an error, if there is any.
func (c *FakeGroupMemberses) Update(ctx context.Context, groupMembers *v1alpha1.GroupMembers, opts v1.UpdateOptions) (result *v1alpha1.GroupMembers, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(groupmembersesResource, groupMembers), &v1alpha1.GroupMembers{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GroupMembers), err
}

// Delete takes name of the groupMembers and deletes it. Returns an error if one occurs.
func (c *FakeGroupMemberses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(groupmembersesResource, name), &v1alpha1.GroupMembers{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGroupMemberses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(groupmembersesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GroupMembersList{})
	return err
}

// Patch applies the patch and returns the patched groupMembers.
func (c *FakeGroupMemberses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GroupMembers, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(groupmembersesResource, name, pt, data, subresources...), &v1alpha1.GroupMembers{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GroupMembers), err
}
