/*
Copyright 2021 The Everoute Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/everoute/everoute/pkg/apis/group/v1alpha1"
)

// FakeGroupMembersPatches implements GroupMembersPatchInterface
type FakeGroupMembersPatches struct {
	Fake *FakeGroupV1alpha1
}

var groupmemberspatchesResource = schema.GroupVersionResource{Group: "group.everoute.io", Version: "v1alpha1", Resource: "groupmemberspatches"}

var groupmemberspatchesKind = schema.GroupVersionKind{Group: "group.everoute.io", Version: "v1alpha1", Kind: "GroupMembersPatch"}

// Get takes name of the groupMembersPatch, and returns the corresponding groupMembersPatch object, and an error if there is any.
func (c *FakeGroupMembersPatches) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GroupMembersPatch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(groupmemberspatchesResource, name), &v1alpha1.GroupMembersPatch{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GroupMembersPatch), err
}

// List takes label and field selectors, and returns the list of GroupMembersPatches that match those selectors.
func (c *FakeGroupMembersPatches) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GroupMembersPatchList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(groupmemberspatchesResource, groupmemberspatchesKind, opts), &v1alpha1.GroupMembersPatchList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GroupMembersPatchList{ListMeta: obj.(*v1alpha1.GroupMembersPatchList).ListMeta}
	for _, item := range obj.(*v1alpha1.GroupMembersPatchList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested groupMembersPatches.
func (c *FakeGroupMembersPatches) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(groupmemberspatchesResource, opts))
}

// Create takes the representation of a groupMembersPatch and creates it.  Returns the server's representation of the groupMembersPatch, and an error, if there is any.
func (c *FakeGroupMembersPatches) Create(ctx context.Context, groupMembersPatch *v1alpha1.GroupMembersPatch, opts v1.CreateOptions) (result *v1alpha1.GroupMembersPatch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(groupmemberspatchesResource, groupMembersPatch), &v1alpha1.GroupMembersPatch{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GroupMembersPatch), err
}

// Update takes the representation of a groupMembersPatch and updates it. Returns the server's representation of the groupMembersPatch, and an error, if there is any.
func (c *FakeGroupMembersPatches) Update(ctx context.Context, groupMembersPatch *v1alpha1.GroupMembersPatch, opts v1.UpdateOptions) (result *v1alpha1.GroupMembersPatch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(groupmemberspatchesResource, groupMembersPatch), &v1alpha1.GroupMembersPatch{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GroupMembersPatch), err
}

// Delete takes name of the groupMembersPatch and deletes it. Returns an error if one occurs.
func (c *FakeGroupMembersPatches) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(groupmemberspatchesResource, name), &v1alpha1.GroupMembersPatch{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGroupMembersPatches) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(groupmemberspatchesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GroupMembersPatchList{})
	return err
}

// Patch applies the patch and returns the patched groupMembersPatch.
func (c *FakeGroupMembersPatches) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GroupMembersPatch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(groupmemberspatchesResource, name, pt, data, subresources...), &v1alpha1.GroupMembersPatch{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GroupMembersPatch), err
}
