/*
Copyright 2021 The Lynx Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/smartxworks/lynx/pkg/apis/group/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVPortGroups implements VPortGroupInterface
type FakeVPortGroups struct {
	Fake *FakeGroupV1alpha1
}

var vportgroupsResource = schema.GroupVersionResource{Group: "group.lynx.smartx.com", Version: "v1alpha1", Resource: "vportgroups"}

var vportgroupsKind = schema.GroupVersionKind{Group: "group.lynx.smartx.com", Version: "v1alpha1", Kind: "VPortGroup"}

// Get takes name of the vPortGroup, and returns the corresponding vPortGroup object, and an error if there is any.
func (c *FakeVPortGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VPortGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(vportgroupsResource, name), &v1alpha1.VPortGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPortGroup), err
}

// List takes label and field selectors, and returns the list of VPortGroups that match those selectors.
func (c *FakeVPortGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VPortGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(vportgroupsResource, vportgroupsKind, opts), &v1alpha1.VPortGroupList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VPortGroupList{ListMeta: obj.(*v1alpha1.VPortGroupList).ListMeta}
	for _, item := range obj.(*v1alpha1.VPortGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vPortGroups.
func (c *FakeVPortGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(vportgroupsResource, opts))
}

// Create takes the representation of a vPortGroup and creates it.  Returns the server's representation of the vPortGroup, and an error, if there is any.
func (c *FakeVPortGroups) Create(ctx context.Context, vPortGroup *v1alpha1.VPortGroup, opts v1.CreateOptions) (result *v1alpha1.VPortGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(vportgroupsResource, vPortGroup), &v1alpha1.VPortGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPortGroup), err
}

// Update takes the representation of a vPortGroup and updates it. Returns the server's representation of the vPortGroup, and an error, if there is any.
func (c *FakeVPortGroups) Update(ctx context.Context, vPortGroup *v1alpha1.VPortGroup, opts v1.UpdateOptions) (result *v1alpha1.VPortGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(vportgroupsResource, vPortGroup), &v1alpha1.VPortGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPortGroup), err
}

// Delete takes name of the vPortGroup and deletes it. Returns an error if one occurs.
func (c *FakeVPortGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(vportgroupsResource, name), &v1alpha1.VPortGroup{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVPortGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(vportgroupsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VPortGroupList{})
	return err
}

// Patch applies the patch and returns the patched vPortGroup.
func (c *FakeVPortGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VPortGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(vportgroupsResource, name, pt, data, subresources...), &v1alpha1.VPortGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPortGroup), err
}
