apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: everoute-clean
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: everoute
      component: everoute-clean
  template:
    metadata:
      labels:
        app: everoute
        component: everoute-clean
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: everoute-clean
          image: everoute/release
          imagePullPolicy: IfNotPresent
          command: ["everoute-clean"]
          readinessProbe:
            exec:
              command: ["test", "-e", "/tmp/everoute_clean_finish"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: everoute-agent
              mountPath: /var/lib/everoute/
            - name: everoute-run
              mountPath: /var/run/everoute/
            - name: host-proc
              mountPath: /host/proc/
            - name: host-netns
              mountPath: /host/var/run/netns/
              mountPropagation: HostToContainer
            - name: cni-bin
              mountPath: /opt/cni/bin/
            - name: everoute-ipam
              mountPath: /var/lib/cni/networks/everoute
            - name: xtables-lock
              mountPath: /run/xtables.lock
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
        - hostPath:
            path: /var/lib/everoute/
          name: everoute-agent
        - hostPath:
            path: /var/lib/cni/networks/everoute
          name: everoute-ipam
        - hostPath:
            path: /opt/cni/bin/
          name: cni-bin
        - name: everoute-run
          hostPath:
            path: /var/run/everoute
        - hostPath:
            path: /etc/cni/net.d
          name: cni-conf
        - hostPath:
            path: /proc
          name: host-proc
        - hostPath:
            path: /var/run/netns
          name: host-netns
        - hostPath:
            path: /lib/modules
          name: host-lib-modules
        - hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
          name: xtables-lock
