/*
Copyright The Everoute Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/everoute/everoute/pkg/apis/pod/v1alpha1"
)

// FakeK8sClusters implements K8sClusterInterface
type FakeK8sClusters struct {
	Fake *FakePodV1alpha1
	ns   string
}

var k8sclustersResource = v1alpha1.SchemeGroupVersion.WithResource("k8scluster")

var k8sclustersKind = v1alpha1.SchemeGroupVersion.WithKind("K8sCluster")

// Get takes name of the k8sCluster, and returns the corresponding k8sCluster object, and an error if there is any.
func (c *FakeK8sClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.K8sCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(k8sclustersResource, c.ns, name), &v1alpha1.K8sCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.K8sCluster), err
}

// List takes label and field selectors, and returns the list of K8sClusters that match those selectors.
func (c *FakeK8sClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.K8sClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(k8sclustersResource, k8sclustersKind, c.ns, opts), &v1alpha1.K8sClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.K8sClusterList{ListMeta: obj.(*v1alpha1.K8sClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.K8sClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested k8sClusters.
func (c *FakeK8sClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(k8sclustersResource, c.ns, opts))

}

// Create takes the representation of a k8sCluster and creates it.  Returns the server's representation of the k8sCluster, and an error, if there is any.
func (c *FakeK8sClusters) Create(ctx context.Context, k8sCluster *v1alpha1.K8sCluster, opts v1.CreateOptions) (result *v1alpha1.K8sCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(k8sclustersResource, c.ns, k8sCluster), &v1alpha1.K8sCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.K8sCluster), err
}

// Update takes the representation of a k8sCluster and updates it. Returns the server's representation of the k8sCluster, and an error, if there is any.
func (c *FakeK8sClusters) Update(ctx context.Context, k8sCluster *v1alpha1.K8sCluster, opts v1.UpdateOptions) (result *v1alpha1.K8sCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(k8sclustersResource, c.ns, k8sCluster), &v1alpha1.K8sCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.K8sCluster), err
}

// Delete takes name of the k8sCluster and deletes it. Returns an error if one occurs.
func (c *FakeK8sClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(k8sclustersResource, c.ns, name, opts), &v1alpha1.K8sCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeK8sClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(k8sclustersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.K8sClusterList{})
	return err
}

// Patch applies the patch and returns the patched k8sCluster.
func (c *FakeK8sClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.K8sCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(k8sclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.K8sCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.K8sCluster), err
}
