/*
Copyright The Everoute Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/everoute/everoute/pkg/apis/service/v1alpha1"
)

// FakeServicePorts implements ServicePortInterface
type FakeServicePorts struct {
	Fake *FakeServiceV1alpha1
	ns   string
}

var serviceportsResource = v1alpha1.SchemeGroupVersion.WithResource("serviceports")

var serviceportsKind = v1alpha1.SchemeGroupVersion.WithKind("ServicePort")

// Get takes name of the servicePort, and returns the corresponding servicePort object, and an error if there is any.
func (c *FakeServicePorts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ServicePort, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(serviceportsResource, c.ns, name), &v1alpha1.ServicePort{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServicePort), err
}

// List takes label and field selectors, and returns the list of ServicePorts that match those selectors.
func (c *FakeServicePorts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ServicePortList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(serviceportsResource, serviceportsKind, c.ns, opts), &v1alpha1.ServicePortList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ServicePortList{ListMeta: obj.(*v1alpha1.ServicePortList).ListMeta}
	for _, item := range obj.(*v1alpha1.ServicePortList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested servicePorts.
func (c *FakeServicePorts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(serviceportsResource, c.ns, opts))

}

// Create takes the representation of a servicePort and creates it.  Returns the server's representation of the servicePort, and an error, if there is any.
func (c *FakeServicePorts) Create(ctx context.Context, servicePort *v1alpha1.ServicePort, opts v1.CreateOptions) (result *v1alpha1.ServicePort, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(serviceportsResource, c.ns, servicePort), &v1alpha1.ServicePort{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServicePort), err
}

// Update takes the representation of a servicePort and updates it. Returns the server's representation of the servicePort, and an error, if there is any.
func (c *FakeServicePorts) Update(ctx context.Context, servicePort *v1alpha1.ServicePort, opts v1.UpdateOptions) (result *v1alpha1.ServicePort, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(serviceportsResource, c.ns, servicePort), &v1alpha1.ServicePort{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServicePort), err
}

// Delete takes name of the servicePort and deletes it. Returns an error if one occurs.
func (c *FakeServicePorts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(serviceportsResource, c.ns, name, opts), &v1alpha1.ServicePort{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServicePorts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(serviceportsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ServicePortList{})
	return err
}

// Patch applies the patch and returns the patched servicePort.
func (c *FakeServicePorts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ServicePort, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(serviceportsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ServicePort{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServicePort), err
}
