/*
Copyright 2021 The Everoute Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	v1alpha1 "github.com/everoute/everoute/pkg/apis/group/v1alpha1"
)

// EndpointGroupLister helps list EndpointGroups.
type EndpointGroupLister interface {
	// List lists all EndpointGroups in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.EndpointGroup, err error)
	// Get retrieves the EndpointGroup from the index for a given name.
	Get(name string) (*v1alpha1.EndpointGroup, error)
	EndpointGroupListerExpansion
}

// endpointGroupLister implements the EndpointGroupLister interface.
type endpointGroupLister struct {
	indexer cache.Indexer
}

// NewEndpointGroupLister returns a new EndpointGroupLister.
func NewEndpointGroupLister(indexer cache.Indexer) EndpointGroupLister {
	return &endpointGroupLister{indexer: indexer}
}

// List lists all EndpointGroups in the indexer.
func (s *endpointGroupLister) List(selector labels.Selector) (ret []*v1alpha1.EndpointGroup, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.EndpointGroup))
	})
	return ret, err
}

// Get retrieves the EndpointGroup from the index for a given name.
func (s *endpointGroupLister) Get(name string) (*v1alpha1.EndpointGroup, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("endpointgroup"), name)
	}
	return obj.(*v1alpha1.EndpointGroup), nil
}
