/*
Copyright The Everoute Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	v1alpha1 "github.com/everoute/everoute/pkg/apis/group/v1alpha1"
)

// GroupMembersLister helps list GroupMemberses.
type GroupMembersLister interface {
	// List lists all GroupMemberses in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.GroupMembers, err error)
	// Get retrieves the GroupMembers from the index for a given name.
	Get(name string) (*v1alpha1.GroupMembers, error)
	GroupMembersListerExpansion
}

// groupMembersLister implements the GroupMembersLister interface.
type groupMembersLister struct {
	indexer cache.Indexer
}

// NewGroupMembersLister returns a new GroupMembersLister.
func NewGroupMembersLister(indexer cache.Indexer) GroupMembersLister {
	return &groupMembersLister{indexer: indexer}
}

// List lists all GroupMemberses in the indexer.
func (s *groupMembersLister) List(selector labels.Selector) (ret []*v1alpha1.GroupMembers, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.GroupMembers))
	})
	return ret, err
}

// Get retrieves the GroupMembers from the index for a given name.
func (s *groupMembersLister) Get(name string) (*v1alpha1.GroupMembers, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("groupmembers"), name)
	}
	return obj.(*v1alpha1.GroupMembers), nil
}
