/*
Copyright The Everoute Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/everoute/everoute/pkg/apis/security/v1alpha1"
)

// FakeGlobalPolicies implements GlobalPolicyInterface
type FakeGlobalPolicies struct {
	Fake *FakeSecurityV1alpha1
}

var globalpoliciesResource = schema.GroupVersionResource{Group: "security.everoute.io", Version: "v1alpha1", Resource: "globalpolicies"}

var globalpoliciesKind = schema.GroupVersionKind{Group: "security.everoute.io", Version: "v1alpha1", Kind: "GlobalPolicy"}

// Get takes name of the globalPolicy, and returns the corresponding globalPolicy object, and an error if there is any.
func (c *FakeGlobalPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GlobalPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(globalpoliciesResource, name), &v1alpha1.GlobalPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalPolicy), err
}

// List takes label and field selectors, and returns the list of GlobalPolicies that match those selectors.
func (c *FakeGlobalPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GlobalPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(globalpoliciesResource, globalpoliciesKind, opts), &v1alpha1.GlobalPolicyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GlobalPolicyList{ListMeta: obj.(*v1alpha1.GlobalPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.GlobalPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested globalPolicies.
func (c *FakeGlobalPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(globalpoliciesResource, opts))
}

// Create takes the representation of a globalPolicy and creates it.  Returns the server's representation of the globalPolicy, and an error, if there is any.
func (c *FakeGlobalPolicies) Create(ctx context.Context, globalPolicy *v1alpha1.GlobalPolicy, opts v1.CreateOptions) (result *v1alpha1.GlobalPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(globalpoliciesResource, globalPolicy), &v1alpha1.GlobalPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalPolicy), err
}

// Update takes the representation of a globalPolicy and updates it. Returns the server's representation of the globalPolicy, and an error, if there is any.
func (c *FakeGlobalPolicies) Update(ctx context.Context, globalPolicy *v1alpha1.GlobalPolicy, opts v1.UpdateOptions) (result *v1alpha1.GlobalPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(globalpoliciesResource, globalPolicy), &v1alpha1.GlobalPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalPolicy), err
}

// Delete takes name of the globalPolicy and deletes it. Returns an error if one occurs.
func (c *FakeGlobalPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(globalpoliciesResource, name), &v1alpha1.GlobalPolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGlobalPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(globalpoliciesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GlobalPolicyList{})
	return err
}

// Patch applies the patch and returns the patched globalPolicy.
func (c *FakeGlobalPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GlobalPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(globalpoliciesResource, name, pt, data, subresources...), &v1alpha1.GlobalPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalPolicy), err
}
