/*
Copyright 2021 The Everoute Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v1alpha1 "github.com/everoute/everoute/pkg/apis/security/v1alpha1"
	scheme "github.com/everoute/everoute/pkg/client/clientset_generated/clientset/scheme"
)

// GlobalPoliciesGetter has a method to return a GlobalPolicyInterface.
// A group's client should implement this interface.
type GlobalPoliciesGetter interface {
	GlobalPolicies() GlobalPolicyInterface
}

// GlobalPolicyInterface has methods to work with GlobalPolicy resources.
type GlobalPolicyInterface interface {
	Create(ctx context.Context, globalPolicy *v1alpha1.GlobalPolicy, opts v1.CreateOptions) (*v1alpha1.GlobalPolicy, error)
	Update(ctx context.Context, globalPolicy *v1alpha1.GlobalPolicy, opts v1.UpdateOptions) (*v1alpha1.GlobalPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GlobalPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GlobalPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GlobalPolicy, err error)
	GlobalPolicyExpansion
}

// globalPolicies implements GlobalPolicyInterface
type globalPolicies struct {
	client rest.Interface
}

// newGlobalPolicies returns a GlobalPolicies
func newGlobalPolicies(c *SecurityV1alpha1Client) *globalPolicies {
	return &globalPolicies{
		client: c.RESTClient(),
	}
}

// Get takes name of the globalPolicy, and returns the corresponding globalPolicy object, and an error if there is any.
func (c *globalPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GlobalPolicy, err error) {
	result = &v1alpha1.GlobalPolicy{}
	err = c.client.Get().
		Resource("globalpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GlobalPolicies that match those selectors.
func (c *globalPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GlobalPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GlobalPolicyList{}
	err = c.client.Get().
		Resource("globalpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested globalPolicies.
func (c *globalPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("globalpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a globalPolicy and creates it.  Returns the server's representation of the globalPolicy, and an error, if there is any.
func (c *globalPolicies) Create(ctx context.Context, globalPolicy *v1alpha1.GlobalPolicy, opts v1.CreateOptions) (result *v1alpha1.GlobalPolicy, err error) {
	result = &v1alpha1.GlobalPolicy{}
	err = c.client.Post().
		Resource("globalpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(globalPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a globalPolicy and updates it. Returns the server's representation of the globalPolicy, and an error, if there is any.
func (c *globalPolicies) Update(ctx context.Context, globalPolicy *v1alpha1.GlobalPolicy, opts v1.UpdateOptions) (result *v1alpha1.GlobalPolicy, err error) {
	result = &v1alpha1.GlobalPolicy{}
	err = c.client.Put().
		Resource("globalpolicies").
		Name(globalPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(globalPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the globalPolicy and deletes it. Returns an error if one occurs.
func (c *globalPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("globalpolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *globalPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("globalpolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched globalPolicy.
func (c *globalPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GlobalPolicy, err error) {
	result = &v1alpha1.GlobalPolicy{}
	err = c.client.Patch(pt).
		Resource("globalpolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
