/*
Copyright 2021 The Lynx Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/smartxworks/lynx/pkg/apis/security/v1alpha1"
	scheme "github.com/smartxworks/lynx/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VPortsGetter has a method to return a VPortInterface.
// A group's client should implement this interface.
type VPortsGetter interface {
	VPorts() VPortInterface
}

// VPortInterface has methods to work with VPort resources.
type VPortInterface interface {
	Create(ctx context.Context, vPort *v1alpha1.VPort, opts v1.CreateOptions) (*v1alpha1.VPort, error)
	Update(ctx context.Context, vPort *v1alpha1.VPort, opts v1.UpdateOptions) (*v1alpha1.VPort, error)
	UpdateStatus(ctx context.Context, vPort *v1alpha1.VPort, opts v1.UpdateOptions) (*v1alpha1.VPort, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VPort, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VPortList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VPort, err error)
	VPortExpansion
}

// vPorts implements VPortInterface
type vPorts struct {
	client rest.Interface
}

// newVPorts returns a VPorts
func newVPorts(c *SecurityV1alpha1Client) *vPorts {
	return &vPorts{
		client: c.RESTClient(),
	}
}

// Get takes name of the vPort, and returns the corresponding vPort object, and an error if there is any.
func (c *vPorts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VPort, err error) {
	result = &v1alpha1.VPort{}
	err = c.client.Get().
		Resource("vports").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VPorts that match those selectors.
func (c *vPorts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VPortList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VPortList{}
	err = c.client.Get().
		Resource("vports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vPorts.
func (c *vPorts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("vports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vPort and creates it.  Returns the server's representation of the vPort, and an error, if there is any.
func (c *vPorts) Create(ctx context.Context, vPort *v1alpha1.VPort, opts v1.CreateOptions) (result *v1alpha1.VPort, err error) {
	result = &v1alpha1.VPort{}
	err = c.client.Post().
		Resource("vports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vPort).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vPort and updates it. Returns the server's representation of the vPort, and an error, if there is any.
func (c *vPorts) Update(ctx context.Context, vPort *v1alpha1.VPort, opts v1.UpdateOptions) (result *v1alpha1.VPort, err error) {
	result = &v1alpha1.VPort{}
	err = c.client.Put().
		Resource("vports").
		Name(vPort.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vPort).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *vPorts) UpdateStatus(ctx context.Context, vPort *v1alpha1.VPort, opts v1.UpdateOptions) (result *v1alpha1.VPort, err error) {
	result = &v1alpha1.VPort{}
	err = c.client.Put().
		Resource("vports").
		Name(vPort.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vPort).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vPort and deletes it. Returns an error if one occurs.
func (c *vPorts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("vports").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vPorts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("vports").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vPort.
func (c *vPorts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VPort, err error) {
	result = &v1alpha1.VPort{}
	err = c.client.Patch(pt).
		Resource("vports").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
